server:
  ssl:
    enabled: true
    key-store: classpath:https_keystore.p12
    key-alias: 1
    key-store-password: chujian
    key-store-type: PKCS12
  port: 8443
  http-port: 8080
spring:
  url: jdbc:mysql://10.201.0.8:3306/user_auth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xqKKZ5xS%m!V^2pc
    hikari:
      minimum-idle: 50
      maximum-pool-size: 500
      connection-timeout: 30000
      connection-test-query: select 1 from dual
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
management:
  endpoints:
    web:
      exposure:
        include: '*'
huawei:
  user-login:
    enable-verify: false
chujian:
  main-account: email
  password:
    enable-encode: true
  visitor:
    enable: true
    username-prefix:
  channel-user-login:
    enable-verify: false
  jwt:
    key:
      enable: true
      jks-filepath: chujian.jks
      password: password
      alias: chujian
#logging:
#  level:
#    root: debug